INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (1,'Adesivo transdérmico','adesivo transdermico');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (2,'Aer bucal (fr de 200 doses)','aer bucal (fr de 200 doses)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (3,'Aerossol','aerossol');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (4,'Aerossol nasal','aerossol nasal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (5,'Aerossol oral','aerossol oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (6,'Amp','amp');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (7,'Bastão','bastao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (8,'Bisnaga','bisnaga');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (9,'Cap','cap');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (10,'Cap liberação controlada','cap liberacao controlada');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (11,'Carpule','carpule');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (12,'Comp','comp');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (13,'Comp rev','comp rev');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (14,'Comprimido','comprimido');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (15,'Comprimido de liberação controlada','comprimido de liberacao controlada');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (16,'Comprimido de liberação prolongada','comprimido de liberacao prolongada');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (17,'Comprimido efervescente','comprimido efervescente');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (18,'Comprimido mastigável','comprimido mastigavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (19,'Comprimido para  suspensão','comprimido para  suspensao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (20,'Comprimido sublingual','comprimido sublingual');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (21,'Creme','creme');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (22,'Creme vaginal','creme vaginal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (23,'Creme vaginal + comprimido','creme vaginal + comprimido');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (24,'Cápsula','capsula');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (25,'Cápsula dura de liberação prolongada','capsula dura de liberacao prolongada');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (26,'Cápsula vaginal','capsula vaginal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (27,'Drágea','dragea');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (28,'Elixir','elixir');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (29,'Emulsão','emulsao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (30,'Emulsão dermatológica','emulsao dermatologica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (31,'Emulsão injetável','emulsao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (32,'Emulsão oftálmica','emulsao oftalmica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (33,'Emulsão oral','emulsao oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (34,'Enema','enema');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (35,'Esmalte','esmalte');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (36,'Gel','gel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (37,'Gel creme','gel creme');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (38,'Gel oftálmico','gel oftalmico');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (39,'Gel percutâneo','gel percutaneo');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (40,'Gel vaginal','gel vaginal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (41,'Geléia','geleia');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (42,'Goma de mascar','goma de mascar');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (43,'Granulado','granulado');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (44,'Implante biodegradável para uso oftálmico (intravítreo)','implante biodegradavel para uso oftalmico (intravitreo)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (45,'Inj (fr)','inj (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (46,'Líquido inalante','liquido inalante');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (47,'Loção','locao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (48,'Orabase','orabase');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (49,'Pasta','pasta');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (50,'Pastilha','pastilha');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (51,'Pó liófilo para injetável com sistema de aplicação','po liofilo para injetavel com sistema de aplicacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (52,'Pomada','pomada');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (54,'Pomada oftálmica','pomada oftalmica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (55,'Pomada retal','pomada retal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (56,'Pó','po');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (57,'Pó + diluente','po + diluente');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (58,'Pó liof inj (amp)','po liof inj (amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (59,'Pó liof inj (fr)','po liof inj (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (60,'Pó liof inj (fr-amp ou ser preenc)','po liof inj (fr-amp ou ser preenc)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (61,'Pó liof inj (fr-amp)','po liof inj (fr-amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (62,'Pó liof inj (ser preenc)','po liof inj (ser preenc)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (63,'Pó liofilizado para solução injetável','po liofilizado para solucao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (64,'Pó liofilizado para suspensão injetável','po liofilizado para suspensao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (65,'Pó para dispersão oral','po para dispersao oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (66,'Pó para inalação oral','po para inalacao oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (67,'Pó para solução','po para solucao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (68,'Pó para solução injetável','po para solucao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (69,'Pó para suspensão','po para suspensao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (70,'Pó para suspensão injetável','po para suspensao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (71,'Sabonete','sabonete');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (72,'Sistema intrauterino','sistema intrauterino');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (73,'Sol inj (amp)','sol inj (amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (74,'Sol inj (fr)','sol inj (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (75,'Sol inj (fr-amp ou ser preenc)','sol inj (fr-amp ou ser preenc)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (76,'Sol inj (fr-amp)','sol inj (fr-amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (77,'Sol inj (ser preenc)','sol inj (ser preenc)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (78,'Sol inj ou pó liof inj (fr-amp)','sol inj ou po liof inj (fr-amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (79,'Sol oft (fr)','sol oft (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (80,'Sol oral (fr)','sol oral (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (81,'Solução','solucao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (82,'Solução injetável','solucao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (83,'Solução injetável com sistema de aplicação','solucao injetavel com sistema de aplicacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (84,'Solução injetável ev','solucao injetavel ev');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (85,'Solução injetável im','solucao injetavel im');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (86,'Solução injetável intra-ocular','solucao injetavel intra-ocular');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (87,'Solução nasal','solucao nasal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (88,'Solução oftálmica','solucao oftalmica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (89,'Solução oral','solucao oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (90,'Solução oto-oftálmica','solucao oto-oftalmica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (91,'Solução otológica','solucao otologica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (92,'Solução para inalação','solucao para inalacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (93,'Solução para nebulização','solucao para nebulizacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (94,'Solução tópica','solucao topica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (95,'Spray  nasal','spray  nasal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (96,'Spray  tópico','spray  topico');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (97,'Supositório','supositorio');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (98,'Susp inj (fr-amp)','susp inj (fr-amp)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (99,'Susp oft (fr)','susp oft (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (100,'Susp oral (fr)','susp oral (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (101,'Suspensão injetável','suspensao injetavel');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (102,'Suspensão nasal','suspensao nasal');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (103,'Suspensão oftálmica','suspensao oftalmica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (104,'Suspensão oral','suspensao oral');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (105,'Suspensão otológica','suspensao otologica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (106,'Suspensão para aerossolterapia','suspensao para aerossolterapia');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (107,'Suspensão para instilação','suspensao para instilacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (108,'Suspensão para nebulização','suspensao para nebulizacao');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (109,'Suspensão tópica','suspensao topica');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (110,'Tablete','tablete');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (111,'Tintura','tintura');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (112,'Xampu','xampu');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (113,'Xarope','xarope');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (114,'Xpe (fr)','xpe (fr)');
INSERT INTO forma_farmaceutica(id,nome,nome_filtro) VALUES (115,'Óvulo','ovulo');
