/*
-- Query: SELECT * FROM sghtaboleiro.logradouro
-- Date: 2023-02-27 23:36
*/
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (1,'ACESSO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (2,'ADRO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (4,'ALAMEDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (5,'ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (7,'ATALHO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (8,'AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (9,'BALNEARIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (10,'BELVEDERE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (11,'BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (12,'BLOCO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (13,'BOSQUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (14,'BOULEVARD');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (15,'BAIXA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (16,'CAIS');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (17,'CAMINHO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (19,'CHAPADAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (20,'CONJUNTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (21,'COLONIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (22,'CORREDOR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (23,'CAMPO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (24,'CORREGO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (27,'DESVIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (28,'DISTRITO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (30,'ESCADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (31,'ESTRADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (32,'ESTACAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (33,'ESTADIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (36,'FAVELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (37,'FAZENDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (38,'FERROVIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (39,'FONTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (40,'FEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (43,'FORTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (45,'GALERIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (46,'GRANJA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (50,'ILHA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (52,'JARDIM');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (53,'LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (54,'LARGO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (55,'LAGOA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (56,'LOTEAMENTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (59,'MORRO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (60,'MONTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (62,'PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (63,'PASSEIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (64,'PATIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (65,'PRACA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (67,'PARADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (70,'PRAIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (71,'PROLONGAMENTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (72,'PARQUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (73,'PASSARELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (74,'PASSAGEM');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (76,'PONTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (77,'QUADRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (79,'QUINTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (81,'RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (82,'RAMAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (87,'RECANTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (88,'RETIRO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (89,'RETA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (90,'RODOVIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (91,'RETORNO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (92,'SITIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (94,'SERVIDAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (95,'SETOR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (96,'SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (97,'TRINCHEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (98,'TERMINAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (99,'TREVO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (100,'TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (101,'VIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (103,'VIADUTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (104,'VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (105,'VIELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (106,'VALE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (108,'ZIGUE-ZAGUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (452,'TRECHO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (453,'VEREDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (465,'ARTERIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (468,'ELEVADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (469,'PORTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (470,'BALAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (471,'PARADOURO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (472,'AREA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (473,'JARDINETE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (474,'ESPLANADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (475,'QUINTAS');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (476,'ROTULA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (477,'MARINA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (478,'DESCIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (479,'CIRCULAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (480,'UNIDADE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (481,'CHACARA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (482,'RAMPA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (483,'PONTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (484,'VIA DE PEDESTRE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (485,'CONDOMINIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (486,'NUCLEO HABITACIONAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (487,'RESIDENCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (495,'CANAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (496,'BURACO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (497,'MODULO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (498,'ESTANCIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (499,'LAGO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (500,'NUCLEO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (501,'AEROPORTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (502,'PASSAGEM SUBTERRANEA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (503,'COMPLEXO VIARIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (504,'PRACA DE ESPORTES');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (505,'VIA ELEVADO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (506,'ROTATORIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (507,'1A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (508,'2A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (509,'3A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (510,'4A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (511,'5A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (512,'6A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (513,'7A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (514,'8A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (515,'9A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (516,'10A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (517,'11A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (518,'12A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (519,'13A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (520,'14A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (521,'15A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (522,'16A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (523,'1O ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (524,'2O ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (525,'3O ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (526,'4O ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (527,'5O ALTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (528,'1O BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (529,'2O BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (530,'3O BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (531,'4O BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (532,'5O BECO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (533,'1A PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (534,'2A PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (535,'3A PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (536,'4A PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (537,'5A PARALELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (538,'1A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (539,'2A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (540,'3A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (541,'4A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (542,'5A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (543,'6A SUBIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (544,'1A VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (545,'2A VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (546,'3A VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (547,'4A VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (548,'5A VILA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (549,'1O PARQUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (550,'2O PARQUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (551,'3O PARQUE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (552,'1A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (553,'2A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (554,'3A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (555,'5A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (556,'4A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (557,'6A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (558,'7A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (559,'8A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (560,'9A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (561,'10A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (562,'11A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (563,'12A RUA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (564,'ESTACIONAMENTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (565,'VALA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (566,'RUA DE PEDESTRE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (567,'TUNEL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (568,'VARIANTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (569,'RODO ANEL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (570,'TRAVESSA PARTICULAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (571,'CALCADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (572,'VIA DE ACESSO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (573,'ENTRADA PARTICULAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (645,'ACAMPAMENTO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (646,'VIA EXPRESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (650,'ESTRADA MUNICIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (651,'AVENIDA CONTORNO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (652,'ENTRE QUADRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (653,'RUA DE LIGACAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (654,'AREA ESPECIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (655,'1A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (656,'2A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (657,'3A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (658,'4A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (659,'18A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (660,'19A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (661,'5A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (662,'RECREIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (663,'PARQUE MUNICIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (664,'CONJUNTO MUTIRAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (665,'PARQUE RESIDENCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (666,'VIA LOCAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (667,'ACESSO LOCAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (668,'VIA COLETORA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (669,'RUA PARTICULAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (670,'RUA INTEGRACAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (671,'ESTRADA VELHA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (672,'RUA VELHA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (673,'TRAVESSA VELHA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (674,'ANTIGA ESTRADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (675,'ESTRADA DE LIGACAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (676,'ESTRADA ESTADUAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (677,'AVENIDA MARGINAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (678,'AVENIDA VELHA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (679,'AVENIDA MARGINAL ESQUERDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (680,'AVENIDA MARGINAL DIREITA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (681,'ESTRADA PARTICULAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (682,'ESTRADA ANTIGA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (683,'6A AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (685,'VIA LITORANEA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (686,'CONTORNO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (687,'BLOCOS');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (688,'CICLOVIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (689,'BULEVAR');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (690,'ESCADARIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (691,'PRIMEIRA LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (692,'2A LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (693,'3A LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (694,'QUARTA LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (695,'QUINTA LADEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (696,'PASSAGEM DE PEDESTRES');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (697,'ESTRADA VICINAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (698,'RUA PROJETADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (699,'RUA PRINCIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (700,'TERCEIRA AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (701,'SEGUNDA AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (702,'PASSEIO PUBLICO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (704,'ENTRE BLOCO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (705,'ENSEADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (706,'ILHOTA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (707,'VIA DE PEDESTRES');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (708,'2A TRAVESSA DA RODOVIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (709,'1A TRAVESSA DA RODOVIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (710,'ESTRADA INTERMUNICIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (711,'VIA COSTEIRA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (712,'ESTRADA DE SERVIDAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (713,'COMUNIDADE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (714,'EIXO INDUSTRIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (715,'MERCADO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (716,'EVANGELICA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (717,'CAMPUS');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (718,'PROJECAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (719,'NUCLEO RURAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (720,'MARGEM');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (721,'AREA VERDE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (722,'CONDOMINIO RESIDENCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (723,'CALCADAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (724,'RUELA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (725,'AVENIDA PERIMETRAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (726,'VIA PRINCIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (727,'VIA PEDESTRE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (728,'VIA LATERAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (729,'CAMINHO DE SERVIDAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (730,'AVENIDA MARGINAL NORTE');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (731,'ESTRADA DE FERRO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (732,'EIXO PRINCIPAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (733,'EIXO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (734,'OUTEIRO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (735,'ESTRADA NOVA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (736,'CONJUNTO HABITACIONAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (737,'JARDIM RESIDENCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (738,'ANEL VIARIO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (739,'SERVIDAO DE PASSAGEM');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (740,'17A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (741,'ANTIGA ESTACAO');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (742,'20A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (743,'21A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (744,'22A TRAVESSA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (745,'CONJUNTO RESIDENCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (746,'2A ALAMEDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (747,'VARIANTE DA ESTRADA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (748,'VIA MARGINAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (749,'MODULO COMERCIAL');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (750,'NOVA AVENIDA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (751,'GLEBA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (998,'ALDEIA');
INSERT INTO logradouro (`codigo`,`descricao`) VALUES (999,'INVÁLIDO');