ALTER TABLE medicamento AUTO_INCREMENT = 1001;
ALTER TABLE cep_ibge AUTO_INCREMENT = 1048576;
ALTER TABLE estado AUTO_INCREMENT = 28;
ALTER TABLE municipio AUTO_INCREMENT = 5571;
ALTER TABLE logradouro AUTO_INCREMENT = 1000;

